# Generated by Django 5.2.11 on 2026-07-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('heatmap_image', models.CharField(blank=True, max_length=255, null=True)),
                ('reconstructed_image', models.CharField(blank=True, max_length=255, null=True)),
                ('reconstruction_method', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
